udpechoclient: udpechoclient.c
		gcc -Wall -o udpechoclient udpechoclient.c

udpechoserver: udpechoserver.c
		gcc -Wall -o udpechoserver udpechoserver.c

.PHONY : clean
clean:
	rm -f udpechoclient udpechoserver